# $195c = metadata location of current map (hi = $02)
# Modes: Gp = Grand prix
# Cups: Rk = Rookie, Sp = Super, Hp = Hyper

# Number of tracks in the game
track_count = 16

# Grand prix-related addressing tables
ai_table_base = 0x0368ed 
audio_table_base = 0x00646a 
metadata_array_base = 0x0240a6 
track_screens_array_base = 0x010562 # hi = $07
track_screens_gfx_bases = [0x072a00, 0x076600] 

# Minlib audio tables (currently unused)
audio_notes_table_base = 0x0063d6
audio_pulse_width_table_base = 0x0063a2

# Track name graphics, tilesets and grand prix tilemaps
titles_grand_prix_tileset = 0x07c180
titles_menus_tileset = 0x07b068
titles_nobar_tilemaps_array_base = 0x020edf
titles_bar_tilemaps_array_base = 0x021312

[GpRk1]
class = "GrandPrixTrack"
index = 0

[GpRk2]
class = "GrandPrixTrack"
index = 1

[GpRk3]
class = "GrandPrixTrack"
index = 2

[GpRk4]
class = "GrandPrixTrack"
index = 3
