# $195c = metadata location of current map (hi = $02)
# Modes: Gp = Grand prix
# Cups: Rk = Rookie, Sp = Super, Hp = Hyper

ai_table_base = 0x0368ed
audio_table_base = 0x00646A
metadata_array_base = 0x0240a6
track_screens_array_base = 0x010562

titles_grand_prix_tileset = 0x07c180
titles_menus_tileset = 0x07b068
titles_nobar_tilemaps_array_base = 0x020edf
titles_bar_tilemaps_array_base = 0x021312

[GpRk1]
class = "GrandPrixTrack"
index = 0

[GpRk2]
type = "GrandPrixTrack"
index = 1

[GpRk3]
type = "GrandPrixTrack"
index = 2

[GpRk4]
type = "GrandPrixTrack"
index = 3
