# $195c = metadata location of current map (hi = $02)
# Modes: Gp = Grand prix
# Cups: Rk = Rookie, Sp = Super, Hp = Hyper

[GpRk1]
type = "GrandPrixTrack"
metadata_base = 0x0240dd
title_index = 0
title_ditto_base = 0x020edf
title_ranking_base = 0x021312

[GpRk2]
type = "GrandPrixTrack"
metadata_base = 0x0240f4
title_index = 1
title_ditto_base = 0x020ee7
title_ranking_base = 0x02131a

[GpRk3]
type = "GrandPrixTrack"
metadata_base = 0x0240c6
title_index = 2
title_ditto_base = 0x020eef
title_ranking_base = 0x021322

[GpRk4]
type = "GrandPrixTrack"
metadata_base = 0x02410b
title_index = 3
title_ditto_base = 0x020ef7
title_ranking_base = 0x02132a
